version: '3'

services:
    web:
        container_name: spike_alert
        build: .
        ports:
            - '3030:1337'
        environment:
            - DOCKER=1
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - '27017:27017'
